version: "3.4"

services:

  literate:
    build:
      dockerfile: ./docker/literate.dockerfile
      context: ./
    environment:
      DISPLAY: host.docker.internal:0
    ports:
      - "5001:5000"
    volumes:
      - type: bind
        source: ./
        target: /literate_compiler